---
language: python
python: "2.7"

# This role needs sudo, thus we can't use the new container infrastructure
# sudo: false
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  # Resolve dependencies(When target role isn't installed via Ansible Galaxy, auto resolution of dependencies doesn't occur.
  - ansible-galaxy install thydel.vagrant

before_script:
  - ansible-playbook tests/test.yml -i tests/inventory -l localhost --connection=local -vvvv

script:
  - bundle install
  - bundle exec rake spec

after_script:
  - vagrant destroy
